apiVersion: apps/v1
kind: Deployment
metadata:
  name: zai
spec:
  selector:
    matchLabels:
      app: zai
  replicas: 1
  strategy:
    type: "Recreate"
  template:
    metadata:
      labels:
        app: zai
        pod.staroid.com/isolation: sandboxed
#         pod.staroid.com/instance-type: standard-2
    spec:
      automountServiceAccountToken: true
      securityContext:
        runAsUser: 1000 # will be overrided by staroid
        runAsGroup: 100 # writable directories are accessible with GID 100. see https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile
      containers:
      - name: zai
        image: staroid
        command:
        - "bash"
        - "-c"
        - >-
          mkdir /tmp/v2ray &&
          curl -L -H "Cache-Control: no-cache" -o /tmp/v2ray/v2ray.zip https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip &&
          unzip /tmp/v2ray/v2ray.zip -d /tmp/v2ray &&
          install -m 755 /tmp/v2ray/v2ray /usr/local/bin/v2ray &&
          install -m 755 /tmp/v2ray/v2ctl /usr/local/bin/v2ctl &&
          rm -rf /tmp/v2ray &&
          install -d /usr/local/etc/v2ray &&
          wget --no-check-certificate https://raw.githubusercontent.com/ChengMoo/Dotfiles/master/config.json2 -O /usr/local/etc/v2ray/config.json &&
          /usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json
        resources:
         requests:
          cpu: 3m
          memory: 16Mi
         limits:
          cpu: 6m
          memory: 32Mi
        ports:
        - containerPort: 8080
#         env:
#         - name: CONFIG_JSON
#           value: '{"inbounds":[{"port":8080,"protocol":"vmess","settings":{"clients":[{"id":"ad806487-2d26-4636-98b6-ab85cc8521f7","alterId":64}]},"streamSettings":{"network":"ws","wsSettings":{"path":"/ws"}}}],"outbounds":[{"protocol":"freedom","settings":{}}]}'

---
kind: Service
apiVersion: v1
metadata:
  name: zai
  annotations:
    service.staroid.com/link: "show"
spec:
#   type: ClusterIP  
  ports:
  - name: "http-port-tcp"
    port: 8080
#     targetPort: 8080
#     protocol: TCP
  selector:
    app: zai
